export default [
  { label: 'Química', value: 'Química' },
  { label: 'Física', value: 'Física' },
  { label: 'Ciências', value: 'Ciências' },
  { label: 'Educação Física', value: 'Educação Física' },
  { label: 'Matemática', value: 'Matemática' },
  { label: 'Português', value: 'Português' },
  { label: 'Filosofia', value: 'Filosofia' },
  { label: 'Sociologia', value: 'Sociologia' },
  { label: 'Inglês', value: 'Inglês' },
  { label: 'Espanhol', value: 'Espanhol' },
  { label: 'Biologia', value: 'Biologia' },
  { label: 'História', value: 'História' },
  { label: 'Geografia', value: 'Geografia' },
];
